# Generated by Django 4.2.1 on 2023-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_remove_song_bpm_song_youtube_link_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=0),
        ),
    ]
